language: objective-c
script:
  - xctool -project TravisCISample.xcodeproj -scheme TravisCISample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project TravisCISample.xcodeproj -scheme TravisCISample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
